export const SET_USERS = "SET_USERS";
export const SET_TOTAL_COUNT = "SET_TOTAL_COUNT";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_CURRENT_USER_REPO = "SET_CURRENT_USER_REPO";
